[package]
name = "life_the_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
libc = "0.2.149"

[profile.release]
lto = true
strip = "debuginfo"
